### ISSUE TITLE
build error immersive ads

### ISSUE THREAD

**Issue by devunity92** [GreedyGame/sdkone-unity_native_ads_plugin#2]
Unity version: 2021.2.19f1
Google Mobile Ads Unity plugin version: 8.6.0
immersive ads unity plugin version: 1.3.1 , 1.4.0
Platform: Android, Unity Editor
Mediation ad networks used - no

I upgrade the SDK from 1.2.8 to 1.3.1 and got this message when build:

C:\Program Files\Unity\Hub\Editor\2021.2.19f1\Editor\Data\il2cpp\build\deploy\il2cpp.exe @Library\Bee\artifacts\rsp\3618536344475536572.rsp
Error: IL2CPP error for method 'System.Void PubScale.SdkOne.PubScaleManager::(System.String)' in assembly 'E:\2024Games\knockBottle\knock\Library\Bee\artifacts\Android\ManagedStripped\PubScale.SdkOne.dll'
System.ArgumentException: An item with the same key has already been added. Key: PubScaleManager_U0E_mF1D68C59CAEB3A26409EDB4F64D62BA45D595B72_MetadataUsageId
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Unity.IL2CPP.CodeWriters.InMemoryGeneratedMethodCodeWriter.AddMetadataUsage(String identifier, MethodMetadataUsage usage)
   at Unity.IL2CPP.CodeWriters.CodeWriterExtensions.WriteMethodWithMetadataInitialization(IGeneratedMethodCodeWriter writer, String methodSignature, Action`2 writeMethodBody, String uniqueIdentifier, MethodReference methodRef, Boolean writingMethodBody)
   at Unity.IL2CPP.MethodWriter.WriteMethodDefinition(AssemblyWriteContext context, IGeneratedMethodCodeWriter writer, MethodReference method)
   at Unity.IL2CPP.SourceWriter.WriteTypesMethods(SourceWritingContext context, IGeneratedMethodCodeWriter writer, TypeWritingInformation& writingInformation, NPath filePath, Boolean writeMarshalingDefinitions)
   at Unity.IL2CPP.SourceWriters.SourceWriterBase`2.WriteItem(StreamWorkItemData`2 data)
   at Unity.IL2CPP.Contexts.Scheduling.Streams.FileLevelParallelStreamManager`3.WorkerWriteItemsToFile(WorkItemData`2 data)
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data)
Error: IL2CPP error (no further information about what managed code was being converted is available)
System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.ArgumentException: Unhandled compare for
System.Void /::()
and
System.Void /::()

Assembly Qualified Names were
System.Void, mscorlib +, PubScale.SdkOne::()
and
System.Void, mscorlib +, PubScale.SdkOne::()

**Comment by GreedyBM** [comment]
Hi @devunity92, Can you build using an LTS version of Unity such as 2021.3.36f1, and let us know if the build issue persists

**Comment by devunity92** [comment]
i am not getting build error in  2021.3 unity versions only in 2021.2 unity getting build error

**Comment by devunity92** [comment]
if i update my game to 2021.3 unity version no build error but my game have some issues with new unity versions. you have any solution for 2021.2 version please share me

**Comment by GreedyBM** [comment]
Unfortunately not @devunity92 as this is not a bug with the SDK but an IL2CPP bug in some Unity editor versions and 2021.2.19f1 happens to be one of them. What you could do is instead of jumping to the LTS version try a later version in 2021.2 series to keep the delta minimum

**Comment by devunity92** [comment]
ok thank u..
